version: "3.9"

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - cico_project/.env.db
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    env_file:
      - cico_project/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data: